[cosmic-ray]
# 変異させたいモジュール/パッケージ（ファイル or ディレクトリ or その配列）
module-path = ["src"]
timeout = 30.0
excluded-modules = ["**/tests/**", "**/test/**"]

# pytest で実行。src レイアウトなら PYTHONPATH=.
test-command = "pytest -q -x"

[cosmic-ray.distributor]
name = "local"     # まずはローカルで直列実行

#[cosmic-ray.filters.operators-filter]
#exclude-operators = ["^core/"]

[tool.setuptools.packages.find]
where = ["."]
include = ["cr_xmt*"]

[project.entry-points."cosmic_ray.operator_providers"]
cr_xmt = "cr_xmt.provider:Provider"